# This is taken from https://github.com/Area69Lab/Recovery-Builder-NoKernel
# All credits goes to above repo

name: CI

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: https://github.com/PitchBlackRecoveryProject/manifest_pb
  MANIFEST_BRANCH: android-11.0
  DEVICE: RMX2151
  DT_LINK: https://github.com/Gofaraway71/PBRP_RMX2151
  DT_PATH: device/realme/RMX2151
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initializing environment
      run: |
       # Workaround to provide additional free space for testing.
        #   https://github.com/actions/virtual-environments/issues/2840
        curl https://raw.githubusercontent.com/snjy4/TWRP_BUILD/main/cleanup.sh | bash
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo rm -rf \
         /usr/share/dotnet \
         /etc/mysql \
         /etc/php \
         .cache \
         /var/cache/* \
         /usr/local/share/boost \
         /opt/ \
         /usr/src \
         /root/* \
         /home/runneradmin \
         /snap/* \
         $AGENT_TOOLSDIRECTORY 2>&1 > /dev/null
        sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
        git config --global user.name "Gofaraway71"
        git config --global user.email "aalbatron@gmail.com"
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get clean
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison aria2
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo

    - name: Sync recovery source and device tree
      run: |
        mkdir work
        cd work
        repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
        repo sync -j4
        repo sync
        git clone $DT_LINK --depth=1 --single-branch $DT_PATH

    - name: Build
      run: |
        cd work && export ALLOW_MISSING_DEPENDENCIES=true && . build/envsetup.sh && lunch omni_$DEVICE-eng && make pbrp

    - name: Upload recovery image
      run: |
        cd work/out/target/product/$DEVICE
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet *.zip
